"""
RoadRakshak — SQLAlchemy Database Models

Tables:
  - User        : citizens, municipal workers, admins
  - Report      : road damage reports with AI detection results
  - Cluster     : groups nearby duplicate reports by GPS + damage type
  - Assignment  : links reports to municipal workers for repair
  - Repair      : before/after photos and verification status
"""

from datetime import datetime, timezone

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


# ---------------------------------------------------------------------------
# User
# ---------------------------------------------------------------------------
class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False, index=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)
    role = db.Column(
        db.String(20),
        nullable=False,
        default="citizen",  # citizen | municipal | admin
    )
    created_at = db.Column(
        db.DateTime, nullable=False, default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    reports = db.relationship("Report", backref="reporter", lazy="dynamic")
    assignments = db.relationship("Assignment", backref="assignee", lazy="dynamic")

    def to_dict(self):
        return {
            "id": self.id,
            "username": self.username,
            "email": self.email,
            "role": self.role,
            "created_at": self.created_at.isoformat(),
        }


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
class Report(db.Model):
    __tablename__ = "reports"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)

    # Image paths (relative to uploads/)
    image_path = db.Column(db.String(255), nullable=False)
    annotated_image_path = db.Column(db.String(255), nullable=True)

    # Location
    latitude = db.Column(db.Float, nullable=True)
    longitude = db.Column(db.Float, nullable=True)
    address = db.Column(db.String(500), nullable=True)

    # AI detection results
    damage_type = db.Column(db.String(50), nullable=True)  # pothole, crack, etc.
    confidence = db.Column(db.Float, nullable=True)
    bounding_boxes = db.Column(db.Text, nullable=True)  # JSON string

    # Severity & priority
    severity_score = db.Column(db.Float, nullable=True)  # 1.0 – 10.0
    severity_level = db.Column(db.String(20), nullable=True)  # critical/high/medium/low
    priority = db.Column(db.String(5), nullable=True)  # P1/P2/P3/P4

    # Status tracking
    status = db.Column(
        db.String(20),
        nullable=False,
        default="pending",  # pending | assigned | in_progress | repaired | verified
    )

    # Duplicate clustering
    cluster_id = db.Column(
        db.Integer, db.ForeignKey("clusters.id"), nullable=True
    )

    # Demo flag — MUST be true if generated by fallback detector
    is_demo = db.Column(db.Boolean, nullable=False, default=False)

    # Timestamps
    created_at = db.Column(
        db.DateTime, nullable=False, default=lambda: datetime.now(timezone.utc)
    )
    updated_at = db.Column(
        db.DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    assignment = db.relationship(
        "Assignment", backref="report", uselist=False, lazy="joined"
    )
    repair = db.relationship(
        "Repair", backref="report", uselist=False, lazy="joined"
    )

    def to_dict(self):
        return {
            "id": self.id,
            "user_id": self.user_id,
            "image_path": self.image_path,
            "annotated_image_path": self.annotated_image_path,
            "latitude": self.latitude,
            "longitude": self.longitude,
            "address": self.address,
            "damage_type": self.damage_type,
            "confidence": self.confidence,
            "bounding_boxes": self.bounding_boxes,
            "severity_score": self.severity_score,
            "severity_level": self.severity_level,
            "priority": self.priority,
            "status": self.status,
            "cluster_id": self.cluster_id,
            "is_demo": self.is_demo,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "assignment": self.assignment.to_dict() if self.assignment else None,
            "repair": self.repair.to_dict() if self.repair else None,
        }


# ---------------------------------------------------------------------------
# Cluster  — groups nearby duplicate reports
# ---------------------------------------------------------------------------
class Cluster(db.Model):
    __tablename__ = "clusters"

    id = db.Column(db.Integer, primary_key=True)
    centroid_lat = db.Column(db.Float, nullable=False)
    centroid_lng = db.Column(db.Float, nullable=False)
    radius_meters = db.Column(db.Float, nullable=False, default=50.0)
    damage_type = db.Column(db.String(50), nullable=False)
    report_count = db.Column(db.Integer, nullable=False, default=1)
    worst_priority = db.Column(db.String(5), nullable=True)
    created_at = db.Column(
        db.DateTime, nullable=False, default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    reports = db.relationship("Report", backref="cluster", lazy="dynamic")

    def to_dict(self):
        return {
            "id": self.id,
            "centroid_lat": self.centroid_lat,
            "centroid_lng": self.centroid_lng,
            "radius_meters": self.radius_meters,
            "damage_type": self.damage_type,
            "report_count": self.report_count,
            "worst_priority": self.worst_priority,
            "created_at": self.created_at.isoformat(),
        }


# ---------------------------------------------------------------------------
# Assignment  — links a report to a municipal worker
# ---------------------------------------------------------------------------
class Assignment(db.Model):
    __tablename__ = "assignments"

    id = db.Column(db.Integer, primary_key=True)
    report_id = db.Column(
        db.Integer, db.ForeignKey("reports.id"), nullable=False, unique=True
    )
    assigned_to = db.Column(
        db.Integer, db.ForeignKey("users.id"), nullable=False
    )
    status = db.Column(
        db.String(20),
        nullable=False,
        default="assigned",  # assigned | in_progress | completed
    )
    notes = db.Column(db.Text, nullable=True)
    assigned_at = db.Column(
        db.DateTime, nullable=False, default=lambda: datetime.now(timezone.utc)
    )
    completed_at = db.Column(db.DateTime, nullable=True)

    def to_dict(self):
        return {
            "id": self.id,
            "report_id": self.report_id,
            "assigned_to": self.assigned_to,
            "status": self.status,
            "notes": self.notes,
            "assigned_at": self.assigned_at.isoformat(),
            "completed_at": (
                self.completed_at.isoformat() if self.completed_at else None
            ),
        }


# ---------------------------------------------------------------------------
# Repair  — before/after photos and verification
# ---------------------------------------------------------------------------
class Repair(db.Model):
    __tablename__ = "repairs"

    id = db.Column(db.Integer, primary_key=True)
    report_id = db.Column(
        db.Integer, db.ForeignKey("reports.id"), nullable=False, unique=True
    )
    before_image_path = db.Column(db.String(255), nullable=False)
    after_image_path = db.Column(db.String(255), nullable=False)
    verified = db.Column(db.Boolean, nullable=False, default=False)
    verification_method = db.Column(
        db.String(20),
        nullable=False,
        default="manual",  # manual (no AI verification pretense)
    )
    verified_by = db.Column(db.String(80), nullable=True)  # username or null
    repaired_at = db.Column(
        db.DateTime, nullable=False, default=lambda: datetime.now(timezone.utc)
    )
    verified_at = db.Column(db.DateTime, nullable=True)

    def to_dict(self):
        return {
            "id": self.id,
            "report_id": self.report_id,
            "before_image_path": self.before_image_path,
            "after_image_path": self.after_image_path,
            "verified": self.verified,
            "verification_method": self.verification_method,
            "verified_by": self.verified_by,
            "repaired_at": self.repaired_at.isoformat(),
            "verified_at": (
                self.verified_at.isoformat() if self.verified_at else None
            ),
        }
